// tasks
export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const TOGGLE_TASK_COMPLETION = 'TOGGLE_TASK_COMPLETION';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';
export const ADD_TASK = 'ADD_TASK'

// users
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// filters
export const SET_STATUS_FILTER = 'SET_STATUS_FILTER';
export const SET_USER_FILTER = 'SET_USER_FILTER';
